echo -e "\e[31m This is a sample text message \e[0m "
echo -e "\e[32m This is a sample text message \e[0m "
echo -e "\e[33m This is a sample text message \e[0m "
echo -e "\e[34m This is a sample text message \e[0m "
echo -e "\e[35m This is a sample text message \e[0m "
echo -e "\e[36m This is a sample text message \e[0m "
echo -e "\e[37m This is a sample text message \e[0m "
echo -e "\e[38m This is a sample text message \e[0m "
echo -e "\e[31m Hello \e[0m"
echo -e "\e[32m Hello \e[0m"
echo -e "\e[31;45m Hello \e[0m"
echo -e "\e[31;45m This is a test characters \e[0m"
echo -e "\e[31;46m This is a test characters \e[0m"
echo -e "\e[31;41m This is a test characters \e[0m"
echo -e "\e[33;41m This is a test characters \e[0m"
echo -e "\e[32;41m This is a test characters \e[0m"
echo -e "\e[32;41m This is a test characters \e[0m"
echo -e "\e[32;41m This is a test characters \e[0m"
echo -e "\e[32;43m This is a test characters \e[0m"
echo -e "\e[32;43m This is a test characters \e[0m"
echo -e "\e[32;42m This is a test characters \e[0m"
echo -e "\e[32;44m This is a test characters \e[0m"
echo -e "\e[32;45m This is a test characters \e[0m"
echo -e "\e[32;46m This is a test characters \e[0m"
echo -e "\e[32;47m This is a test characters \e[0m"
echo -e "\e[32;47;4m This is a test characters \e[0m"
echo -e "\e[31;47;4m This is a test characters \e[0m"
echo -e "\e[31;42;4m This is a test characters \e[0m"
echo -e "\e[32;42;4m This is a test characters \e[0m"
echo -e "\e[33;42;4m This is a test characters \e[0m"
echo -e "\e[34;42;4m This is a test characters \e[0m"
echo -e "\e[35;42;4m This is a test characters \e[0m"
echo -e "\e[36;42;4m This is a test characters \e[0m"
echo -e "\e[37;42;4m This is a test characters \e[0m"
echo -e "\e[38;42;4m This is a test characters \e[0m"
echo -e "\e[31;42;4m This is a test characters \e[0m"
